### ISSUE TITLE
Want to fork and build a OPENMP version

### ISSUE THREAD

**Issue by langker** [ActKz/Wave-Equation-2D#1]
Hi, now I am having an Advance Computer Architecture class, which require us to build the wave equation using OPENMP, so I just found this nice project and forked one:) I think maybe you are doing the same thing but using CUDA. Anyway, thank you.

Best Wish,
Xiang Chaoran.

**Comment by ActKz** [comment]
You're welcome ;)
And just for remind, this project didn't visualize the wave.
